# Generated by Django 5.1.7 on 2025-03-17 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carrentalapp', '0002_userprofile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carreturn',
            name='rental',
        ),
        migrations.AlterField(
            model_name='carreturn',
            name='car_picture',
            field=models.ImageField(upload_to='car_returns/'),
        ),
        migrations.AlterField(
            model_name='carreturn',
            name='condition',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='carreturn',
            name='return_date',
            field=models.DateTimeField(),
        ),
    ]
