# Generated by Django 5.1.7 on 2025-03-17 07:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carrentalapp', '0004_carreturn_rental_alter_carreturn_car_picture_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carreturn',
            name='car_picture',
            field=models.ImageField(upload_to='car_returns/'),
        ),
        migrations.AlterField(
            model_name='carreturn',
            name='rental',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='carrentalapp.carrental'),
        ),
        migrations.AlterField(
            model_name='carreturn',
            name='return_date',
            field=models.DateTimeField(),
        ),
    ]
