# Generated by Django 5.1.7 on 2025-03-17 07:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carrentalapp', '0005_alter_carreturn_car_picture_alter_carreturn_rental_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carreturn',
            name='car_picture',
            field=models.ImageField(upload_to='returned_cars/'),
        ),
        migrations.AlterField(
            model_name='carreturn',
            name='rental',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='carrentalapp.carrental'),
        ),
        migrations.AlterField(
            model_name='carreturn',
            name='return_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
